version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
    depends_on:
      - db
    networks:
      - social_network
    command: uvicorn main:app --host 0.0.0.0 --port ${PORT} --reload

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - social_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER}" ]
      interval: 3600s
      timeout: 5s
      retries: 5

networks:
  social_network:
    driver: bridge

volumes:
  postgres_data: