version: '3.8'
# !!! Для внутренних сервисов добавляем сеть backend
networks:
  frontend:
  backend:
    internal: true
services:
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile.prod
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      - PORT=${API_GATEWAY_PORT}
      - NODE_ENV=prod
      - PORT_AUTH_SERVICE=${AUTH_SERVICE_PORT}
      - PORT_STORY_SERVICE=${STORY_SERVICE_PORT}
      - PORT_USER_SERVICE=${USER_SERVICE_PORT}
      - PORT_MEDIA_SERVICE=${MEDIA_SERVICE_PORT}
      - PORT_SOCIAL_SERVICE=${SOCIAL_SERVICE_PORT}
      - PORT_NOTIFICATION_SERVICE=${NOTIFICATION_SERVICE_PORT}
    depends_on:
      - auth-service
    env_file:
      - .env
    networks:
      - frontend
      - backend
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.prod
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - NODE_ENV=prod
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/storycraft_auth
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend