version: '3.8'

services:
  auth-service-prod:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile.prod
    ports:
      - "${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}"
    environment:
      - PORT=${AUTH_SERVICE_PORT}
      - NODE_ENV=prod
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/storycraft_auth
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env