FROM node:20-slim

WORKDIR /app

RUN apt-get update -y && apt-get install -y openssl curl wget

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

CMD ["/bin/sh", "-c", "npm install && npx prisma migrate dev && npm run dev"]