FROM node:23-slim

WORKDIR /app

COPY package*.json ./
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN npm install

COPY . .

RUN npx prisma generate

CMD ["/bin/sh", "-c", "npm install && npx prisma migrate deploy && npm run dev"]